### PR TITLE
Add `.travis.yml` to test the package with CI

### LINKED ISSUE #5: Make Travis work
The setup on the side of Travis has been done some 3 years ago. The PR for adding the correct `.travis.yml` file never completed. We could base it on [zero-to-production continuous-integration](https://www.lpalmieri.com/posts/2020-06-06-zero-to-production-1-setup-toolchain-ides-ci/#5-continuous-integration).

In a [PR](https://github.com/ReinierMaas/morton/pull/3) there is a working version of `.travis.yml`. It would be good to test on `stable`, `beta` and `nightly` channels.

### PR DESCRIPTION
**Pull request by ReinierMaas**
Closes: https://github.com/ReinierMaas/morton/issues/5

By adding CI we ensure continuous quality of the `morton` package.

### CODE REVIEW

**Comment by ReinierMaas** [comment]
Hey @bz2, do you know of any checks for Rust we can add?

Fuzzing our interface would be a separate issue I suppose, see https://github.com/ReinierMaas/morton/issues/8.

**Review by bz2 — APPROVED** [review]
What you have here looks good!

I would be tempted to remove the elements that are informational rather than gating, specifically `tarpaulin` (which says half the code isn't run because it's pointer-width dependent) and the `bench` itself.

**Comment by ReinierMaas** [comment]
I would be tempted to continue to run the benchmark code on CI to ensure it doesn't break.

**Comment by bz2** [comment]
I think that the benches compiling and passing lints would already be a pretty strong indicator?

Go ahead and land and try it out either way!

**Pull request merged**
