### PR TITLE
Make library work on stable release channel

### PR DESCRIPTION
**Pull request by bz2**
Hey @ReinierMaas - thanks for writing this (a few years ago). Looking to use this in a project, but need it to build on the stable channel, which required some code changes, proposed here.

I'd also be happy to adopt the crate and publish if you want to share maintainership.

## Changes

No functional changes.

As bench is still not stable, use bencher crate. Split testing and benchmarks out to their own modules.

Remove template and default elements from cargo file. Update to 2018 edition of Rust.

Bump version to 0.3.0.

Add a little documentation and fix clippy lints.

### CODE REVIEW

**Comment by ReinierMaas** [comment]
Hey thanks for using my code. I once build and used it in a path tracer. On Wednesday 23th I can check the changes.

I could add you as a collaborator would this be enough to sharing the maintainership?

**Comment by bz2** [comment]
Thanks! I think collaborator in your namespace works fine, and [from the cargo book](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner) seems `cargo owner --add bz2 morton` should work for crate publishing.

**Comment by ReinierMaas** [comment]
Hey, I found some time this morning. This looks very good, thanks for building this.

**Comment by bz2** [comment]
Thank you!

**Pull request merged**
